### PR TITLE
Add event hubs code sample for javascript listener / sender

### PR DESCRIPTION
**Pull request by KhaVNguyen**
Derived from this tutorial: https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-node-get-started-send
Will be a quick start for merchants wanting to use code to interact with event hubs data

### CODE REVIEW

**Comment by KhaVNguyen** [comment]
@chadsowald Hey Chad, do you mind giving this a peek when you get the chance? Microsoft Docs for extensibility is currently blocked until this goes through

**Comment by chadsowald** [comment]
@KhaVNguyen Are you still able to comment?  Thanks for this JS event hubs sample.   Is there a reason we need to add this sample considering that it's not Fraud Protection specific?  It seems the the docs you linked to are ultimately a bit more helpful as they have multiple languages and will presumably be updated over time and even possibly expanded.  Why not just have the docs team have a big link to that page?

**Comment by KhaVNguyen** [comment]
Hey @chadsowald. Yep what you said makes perfect sense. I just thought it would be faster if they used the code sample here directly (and they also happen to want to use JS) instead of replicating the steps themselves. That said, we should just link to the existing docs instead to cover all bases.

**Comment by chadsowald** [comment]
Thanks @KhaVNguyen!  I'll ping docs about this to make sure they have that other link and we'll abandon this PR.  Take care!

**Pull request closed without merging**
